# Generated by Django 5.0.2 on 2024-03-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
    ]
