# Generated by Django 5.0.2 on 2024-03-04 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Usuario', 'Usuario'), ('Administrador', 'Administrador')], default='Usuario', max_length=100, verbose_name='Tipo Usuario')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sobrenome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='profile_img', verbose_name='Profile Image')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('phone_number', models.CharField(blank=True, max_length=19, null=True, verbose_name='Número de Telefone')),
                ('gender', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=20, null=True, verbose_name='Gênero')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_acces', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
