# Generated by Django 5.0.2 on 2024-03-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Prefiro não informar', 'Prefiro não informar'), ('Outro', 'Outro')], max_length=20, null=True, verbose_name='Gênero'),
        ),
    ]
