# Generated by Django 5.0.2 on 2024-03-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_alter_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_img',
        ),
        migrations.AddField(
            model_name='profile',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
    ]
